#!/usr/bin/env python3
"""Copy a Pretty HTML PPT template into a safely managed output directory."""

from __future__ import annotations

import argparse
import shutil
import tempfile
from pathlib import Path

from inject_edit_mode import inject_edit_mode
from inject_presenter_mode import inject_presenter_mode


OUTPUT_MARKER = ".pretty-html-ppt-output"
OUTPUT_MARKER_CONTENT = "Generated by Pretty HTML PPT.\n"
VCS_MARKERS = (".git", ".hg", ".svn")


def is_within(path: Path, directory: Path) -> bool:
    """Return whether path is directory itself or one of its descendants."""
    try:
        path.relative_to(directory)
        return True
    except ValueError:
        return False


def available_templates(templates_dir: Path) -> list[str]:
    return sorted(
        item.name
        for item in templates_dir.iterdir()
        if item.is_dir() and not item.is_symlink()
    )


def resolve_template_source(skill_root: Path, style: str) -> Path:
    templates_dir = (skill_root / "assets" / "templates").resolve()
    available = available_templates(templates_dir)
    if style not in available or Path(style).name != style:
        raise SystemExit(f"Unknown style: {style}. Available: {', '.join(available)}")

    source_path = templates_dir / style
    if source_path.is_symlink():
        raise SystemExit(f"Template must not be a symbolic link: {style}")

    source = source_path.resolve()
    if source.parent != templates_dir or not source.is_dir():
        raise SystemExit(f"Template escapes the template library: {style}")
    return source


def resolve_safe_target(output_dir: str, source: Path, skill_root: Path) -> Path:
    requested = Path(output_dir).expanduser()
    if requested.is_symlink():
        raise SystemExit(f"Refusing symbolic-link output directory: {requested}")

    target = requested.resolve()
    root = Path(target.anchor).resolve()
    home = Path.home().resolve()
    cwd = Path.cwd().resolve()
    skill_root = skill_root.resolve()

    if target == root:
        raise SystemExit(f"Refusing filesystem root as output directory: {target}")
    if is_within(home, target):
        raise SystemExit(
            f"Refusing output directory that contains the home directory: {target}"
        )
    if is_within(cwd, target):
        raise SystemExit(
            f"Refusing output directory that contains the working directory: {target}"
        )
    if is_within(source, target):
        raise SystemExit(
            f"Refusing output directory that contains the template source: {target}"
        )
    if is_within(target, source) or is_within(target, skill_root):
        raise SystemExit(
            f"Refusing output directory inside the installed skill: {target}"
        )
    if any(part in VCS_MARKERS for part in target.parts):
        raise SystemExit(
            f"Refusing output directory inside version-control metadata: {target}"
        )
    if target.exists() and any((target / marker).exists() for marker in VCS_MARKERS):
        raise SystemExit(f"Refusing repository root as output directory: {target}")

    return target


def is_managed_output(target: Path) -> bool:
    marker = target / OUTPUT_MARKER
    if marker.is_symlink() or not marker.is_file():
        return False
    try:
        return marker.read_text(encoding="utf-8") == OUTPUT_MARKER_CONTENT
    except OSError:
        return False


def assert_replaceable(target: Path, force: bool) -> bool:
    if not target.exists():
        return False
    if not target.is_dir():
        raise SystemExit(f"Output exists and is not a directory: {target}")
    if not force:
        raise SystemExit(f"Output exists: {target}. Use --force to overwrite.")
    if not is_managed_output(target):
        raise SystemExit(
            "Refusing to overwrite an unmanaged directory. "
            f"Choose a new output directory or remove it manually: {target}"
        )
    return True


def build_staged_output(
    source: Path,
    staged_target: Path,
    no_edit: bool,
    no_presenter: bool,
) -> None:
    shutil.copytree(source, staged_target)
    index_path = staged_target / "index.html"
    if not index_path.is_file():
        raise FileNotFoundError(f"Template is missing index.html: {source}")
    if not no_edit:
        inject_edit_mode(index_path)
    if not no_presenter:
        inject_presenter_mode(index_path)
    (staged_target / OUTPUT_MARKER).write_text(OUTPUT_MARKER_CONTENT, encoding="utf-8")


def install_staged_output(
    staged_target: Path, target: Path, replace_existing: bool
) -> None:
    backup = staged_target.parent / "previous"
    if replace_existing:
        if not target.exists() or not is_managed_output(target):
            raise RuntimeError(f"Output changed while preparing replacement: {target}")
        target.rename(backup)
    elif target.exists():
        raise RuntimeError(f"Output appeared while preparing installation: {target}")

    try:
        staged_target.rename(target)
    except Exception:
        if replace_existing and backup.exists() and not target.exists():
            try:
                backup.rename(target)
            except Exception as rollback_error:
                raise RuntimeError(
                    "Could not install the new output or restore the previous output. "
                    f"The previous output is preserved at: {backup}"
                ) from rollback_error
        raise

    if backup.exists():
        shutil.rmtree(backup)


def copy_template(
    style: str,
    output_dir: str,
    *,
    force: bool = False,
    no_edit: bool = False,
    no_presenter: bool = False,
) -> Path:
    skill_root = Path(__file__).resolve().parents[1]
    source = resolve_template_source(skill_root, style)
    target = resolve_safe_target(output_dir, source, skill_root)
    replace_existing = assert_replaceable(target, force)

    target.parent.mkdir(parents=True, exist_ok=True)
    staging_root = Path(
        tempfile.mkdtemp(prefix=".pretty-html-ppt-stage-", dir=str(target.parent))
    )
    staged_target = staging_root / "new"
    try:
        build_staged_output(source, staged_target, no_edit, no_presenter)
        install_staged_output(staged_target, target, replace_existing)
    finally:
        backup = staging_root / "previous"
        if not backup.exists():
            shutil.rmtree(staging_root, ignore_errors=True)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description="Copy a Pretty HTML PPT template.")
    parser.add_argument("style", help="Style slug, e.g. pastel-blockfolio")
    parser.add_argument(
        "output_dir", help="Dedicated directory to create or safely replace"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an output directory previously generated by this script",
    )
    parser.add_argument(
        "--no-edit",
        action="store_true",
        help="Skip browser edit mode (it is injected by default).",
    )
    parser.add_argument(
        "--presenter",
        action="store_true",
        help="Deprecated compatibility flag. Presenter mode is injected by default.",
    )
    parser.add_argument(
        "--no-presenter",
        action="store_true",
        help="Skip presenter mode with speaker notes, next-slide preview, and timer.",
    )
    args = parser.parse_args()

    target = copy_template(
        args.style,
        args.output_dir,
        force=args.force,
        no_edit=args.no_edit,
        no_presenter=args.no_presenter,
    )
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
