#!/usr/bin/env python3
"""Create a standalone editable HTML PPT scaffold from this skill's base deck."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

from inject_edit_mode import inject_edit_mode
from inject_presenter_mode import inject_presenter_mode


MARKER = ".editable-html-ppt-output"
STYLE_MARKER_START = "<!-- EDITABLE_HTML_PPT_STYLE_START -->"
STYLE_MARKER_END = "<!-- EDITABLE_HTML_PPT_STYLE_END -->"
STYLES = {
    "base": None,
    "editorial-ink": "editorial-ink.css",
    "swiss-grid": "swiss-grid.css",
}


def apply_style(index_path: Path, style: str) -> None:
    """Apply one named visual system without changing the slide markup or runtime."""
    if style not in STYLES:
        raise ValueError(f"Unknown style: {style}. Choose from: {', '.join(STYLES)}")

    html = index_path.read_text(encoding="utf-8")
    html = re.sub(
        rf"\n?{re.escape(STYLE_MARKER_START)}.*?{re.escape(STYLE_MARKER_END)}\n?",
        "\n",
        html,
        flags=re.DOTALL,
    )
    html = re.sub(r"\sdata-deck-style=(?:\"[^\"]*\"|'[^']*')", "", html, count=1)

    stylesheet = STYLES[style]
    if stylesheet:
        style_path = Path(__file__).resolve().parents[1] / "assets" / "styles" / stylesheet
        css = style_path.read_text(encoding="utf-8").strip()
        html = html.replace(
            "<html ",
            f'<html data-deck-style="{style}" ',
            1,
        )
        block = f"\n{STYLE_MARKER_START}\n<style id=\"editable-html-ppt-style\">\n{css}\n</style>\n{STYLE_MARKER_END}\n"
        if "</head>" not in html:
            raise ValueError(f"Missing </head> in {index_path}")
        html = html.replace("</head>", f"{block}</head>", 1)

    index_path.write_text(html, encoding="utf-8")


def create_deck(output_dir: Path, force: bool = False, style: str = "base") -> Path:
    output_dir = output_dir.expanduser().resolve()
    template_dir = Path(__file__).resolve().parents[1] / "assets" / "base-deck"

    if output_dir.exists():
        if not force:
            raise FileExistsError(
                f"Output already exists: {output_dir}. Choose a new directory or use --force "
                "only on a previous editable-html-ppt output."
            )
        if not (output_dir / MARKER).is_file():
            raise FileExistsError(
                f"Refusing to replace an unmanaged directory: {output_dir}. "
                "Choose a new output directory instead."
            )
        shutil.rmtree(output_dir)

    shutil.copytree(template_dir, output_dir)
    index_path = output_dir / "index.html"
    apply_style(index_path, style)
    inject_presenter_mode(index_path)
    inject_edit_mode(index_path)
    (output_dir / MARKER).write_text("editable-html-ppt\n", encoding="utf-8")
    return output_dir


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a standalone HTML PPT scaffold with edit and presenter runtime."
    )
    parser.add_argument("output_dir", help="New output directory")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace only a directory previously generated by this script.",
    )
    parser.add_argument(
        "--style",
        choices=sorted(STYLES),
        default="base",
        help="Visual system: base, editorial-ink, or swiss-grid.",
    )
    args = parser.parse_args()
    try:
        print(create_deck(Path(args.output_dir), force=args.force, style=args.style))
    except (FileExistsError, FileNotFoundError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
